### ISSUE TITLE
discussion: changes for SSD inception v2

### ISSUE THREAD

**Issue by redM0nk** [martinzlocha/anchor-optimization#15]
Hello.
I'm using SSD Inception v2 architecture and want to leverage this script to figure out the best anchor parameters for my custom dataset. In my understanding, the current codebase uses the default parameters for Keras-Retinanet and has some other minor dependencies.

e.g.
![image](https://user-images.githubusercontent.com/6208561/81839315-39c36e80-94fc-11ea-9975-5724f9ed3cf5.png)

I just wanted to initiate the discussion and see if any work has already been done along the line. Also, if required, lay down the list of tasks that are needed to achieve the above objective.

Thank you,
Aneesh

**Comment by martinzlocha** [comment]
Hi Aneesh,

thanks for showing interest in the project. Currently I have no plan to extend this tool to use SSD Inception v2 or other libraries. The fact that I reused retinanet was intentional to avoid introducing bugs by reimplementing the same functions. 

It would be possible to refactor the codebase to reduce the coupling between keras retinanet and this tool if you are interested however I am just maintaining the state of this project and do not plan to iterate on it personally so I think the best way would be for you to fork this. However there are some assumptions made in the codebase about how retinanet works and I am not sure how well it will translate to SSD Inception v2.

Martin

**Comment by redM0nk** [comment]
I appreciate your feedback Martin. It makes sense to fork the repo before starting the new work.

Thank you,
Aneesh
