### ISSUE TITLE
MemoryError: Unable to allocate 2.62 TiB for an array with shape (1250965, 288300) and data type float64

### ISSUE THREAD

**Issue by qtw1998** [martinzlocha/anchor-optimization#16]
MemoryError: Unable to allocate 2.62 TiB for an array with shape (1250965, 288300) and data type float64
![image](https://user-images.githubusercontent.com/34357479/82514747-20986e80-9b49-11ea-9624-3e6b71a8d7f8.png)
How would I solve this problem?

**Comment by Samjith888** [comment]
I got the same error when  i include `--include-stride` this flag. If u removed that flag, then the script will work without error

**Comment by martinzlocha** [comment]
Hi yes, this is because your images are very large and you passed in a lot of samples at once. You have to reduce one of these two things.

**Comment by ChunmianLin** [comment]
@martinzlocha Hi, if few samples  use anchor optimization at once, I think,  the generated anchors cannot represent the distribution of data. Is it?
Also, how to use CUDA or GPU computation for anchor optimization? In my experiment, I infer the process conducts on the CPU kernel due to the unchanged GPU memory.
I would appreciate it if you give me any helpful response!
Thanks!

**Comment by martinzlocha** [comment]
The algorithm is not implemented for a GPU, only CPU can be used. I'm sorry but I don't understand your first part of the question, can you clarify?

**Comment by martinzlocha** [comment]
Closing as there hasn't been any followup. Feel free to reopen if you have anything else.
