### ISSUE TITLE
Base sizes of anchors

### ISSUE THREAD

**Issue by PawelFaron** [martinzlocha/anchor-optimization#20]
Is there a possibility to specify base sizes and strides for calculation?

**Comment by martinzlocha** [comment]
Hi, you shouldn't be modifying strides and base size as those are fixed by the model architecture and cannot be changed.

In theory its possible to modify them however I 95% of the time when people modify them they don't understand what they should be set to and how they are tied to the model architecture so most likely you don't want to do that. https://github.com/martinzlocha/anchor-optimization/blob/master/anchor_optimization/optimize_anchors_argparse.py#L115

**Comment by PawelFaron** [comment]
Yes I know just wanted to use your repo to calculate anchor boxes for different architecture. To be precise I'm training the Hybrid task cascade from mmdetection https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_x101_64x4d_fpn_dconv_c3-c5_mstrain_400_1400_16x1_20e_coco.py

Could you advise if there is possibility to configure your code for that?

**Comment by martinzlocha** [comment]
If you clone the repo and modify the following I don't see why it wouldn't be possible. I don't know the network architecture though so can't help you on the actual sizes and strides.

 - https://github.com/martinzlocha/anchor-optimization/blob/master/anchor_optimization/optimize_anchors_argparse.py#L115

**Comment by martinzlocha** [comment]
Closing as this isn't an issue and there hasn't been any followup. Feel free to reopen if you have anything else.
