### ISSUE TITLE
How to interpret the anchor scale output for a different use?

### ISSUE THREAD

**Issue by pieterblok** [martinzlocha/anchor-optimization#21]
Hello @martinzlocha 

Thank you for the nice anchor-optimization tool!

I was wondering how I can interpret the anchor scale output? Is it a fraction of the default anchor size:
https://github.com/martinzlocha/anchor-optimization/blob/ea21e60cc3b3287d3a8bc66d4befe0014cf664cc/anchor_optimization/optimize_anchors.py#L23

My goal is to optimize the anchor aspect ratios and the scales for YOLACT++. The aspect ratios can be easily copy-pasted, but the scales are in a different format. YOLACT uses absolute values instead of fractions. YOLACT uses a maximum image-size of 550 pixels: https://github.com/dbolya/yolact/blob/57b8f2d95e62e2e649b382f516ab41f949b57239/data/config.py#L664

When I executed the command below:
`anchor-optimization yolact/data/custom/train/boxes.csv --ratios=3 --scales=5 --image-max-side 550`

This output was generated:
`State: 0.12784`
`Ratios: [0.461, 1.0, 2.168]` 
`Scales: [0.4, 0.458, 0.527, 0.689, 1.2]`

I'm a bit confused as the 'pred_scales' of YOLACT are:
`[24, 48, 96, 192, 384]`
https://github.com/dbolya/yolact/blob/57b8f2d95e62e2e649b382f516ab41f949b57239/data/config.py#L779

Can someone help me with the right interpretation?
Thanks in advance,
Pieter

**Comment by martinzlocha** [comment]
I would recommend you have a look at the code which generates the anchor boxes from the configuration. The anchor boxes are generated here: https://github.com/martinzlocha/anchor-optimization/blob/ea21e60cc3b3287d3a8bc66d4befe0014cf664cc/anchor_optimization/optimize_anchors.py#L80

If you look how `base_anchors_for_shape` is implemented it eventually calls: https://github.com/fizyr/keras-retinanet/blob/424671f71da40845e987713544493f4e88f4ea68/keras_retinanet/utils/anchors.py#L278

As the name of the second function suggests, it generates anchors given a specific configuration.

One thing to note is that this algorithm has been written for RetinaNet and I am not sure how well it will generalise for YOLACT++. For example the reason the smallest scale in your results was 0.4 is because thats the lower boundary which I hardcoded here: https://github.com/martinzlocha/anchor-optimization/blob/ea21e60cc3b3287d3a8bc66d4befe0014cf664cc/anchor_optimization/optimize_anchors.py#L238. 

If the value for scales get smaller the anchor boxes get really small and it is better to consider changing the input images (eg making them larger, passing in sections of the image and stitching the results together).

Hope the links help you get a better understanding, let me know if you have other questions.

**Comment by pieterblok** [comment]
> I would recommend you have a look at the code which generates the anchor boxes from the configuration. The anchor boxes are generated here:
> 
> https://github.com/martinzlocha/anchor-optimization/blob/ea21e60cc3b3287d3a8bc66d4befe0014cf664cc/anchor_optimization/optimize_anchors.py#L80
> 
> If you look how `base_anchors_for_shape` is implemented it eventually calls: https://github.com/fizyr/keras-retinanet/blob/424671f71da40845e987713544493f4e88f4ea68/keras_retinanet/utils/anchors.py#L278
> 
> As the name of the second function suggests, it generates anchors given a specific configuration.
> 
> One thing to note is that this algorithm has been written for RetinaNet and I am not sure how well it will generalise for YOLACT++. For example the reason the smallest scale in your results was 0.4 is because thats the lower boundary which I hardcoded here:
> 
> https://github.com/martinzlocha/anchor-optimization/blob/ea21e60cc3b3287d3a8bc66d4befe0014cf664cc/anchor_optimization/optimize_anchors.py#L238
> 
> .
> If the value for scales get smaller the anchor boxes get really small and it is better to consider changing the input images (eg making them larger, passing in sections of the image and stitching the results together).
> 
> Hope the links help you get a better understanding, let me know if you have other questions.

@martinzlocha thank you for your fast and accurate answer. I will have a look at these functions in keras-retinanet. Hopefully I can replicate them in YOLACT++ (I understand the cannot be compared one-on-one). Thanks!
